### ISSUE TITLE
Two issues on Dell Latitude E5470

### ISSUE THREAD

**Issue by PXNDA1234321** [sebanc/brunch#683]
1. Error booting up
    `error: no module found...` (or something similar). Doesn't really affect the machine as far as I know. I just press a key and it boots up normally.

2. INTERNAL MIC NOT WORKING
    This is a bummer for me. I got my mic working on Arch Linux by installing it pulseaudio and I am not sure if I could do something similar on chromeOS. I've looked at other issues but still haven't been able to fix it.

Thanks in advance and thank you sebanc for this awesome project.

**Comment by ameyjoshi3068** [comment]
Hi,
Your first issue seems to be related to grub entry. removing `rmmod tpm` from the first line should fix this issue.

**Comment by sebanc** [comment]
Hi,

ameyjoshi3068 solution is correct for 1.

For 2. it seems the first 5.4 kernel build introduced a regression wrt microphone, I have sent you a github email invite to the "brunch-testing" repo, could you validate it and try the build there ?

If microphone still does not work, could you try to add a space and "options=internal_mic_fix" to your grub config after "cros_debug" ?

**Comment by PXNDA1234321** [comment]
Hey,

Thanks ameyjoshi3068, that fixed it.

sebanc how should I try the build. Would I use this command: `sudo chromeos-update -f` or would I have to remake the .img?

**Comment by sebanc** [comment]
Yes you can use `chromeos-update -f`

**Comment by PXNDA1234321** [comment]
Hey sebanc,

Got an error: `bash: chromeos-update: command not found`

**Comment by PXNDA1234321** [comment]
Hey sebanc,

Got an error: `bash: chromeos-update: command not found`

**Comment by sebanc** [comment]
did you use sudo ?

**Comment by PXNDA1234321** [comment]
Oops, just tried it with sudo and got another error: `Brunch release archive not found`

**Comment by sebanc** [comment]
You don't need to extract the archive.

run: `sudo chromeos-update -f ~/Downloads/<archive_name>`

**Comment by PXNDA1234321** [comment]
Tried the brunch testing repo which, unfortunately, didn't solve the microphone. I am going to try the `options=internal_mic_fix` in grub config.

**Comment by PXNDA1234321** [comment]
Nope, no luck sebanc. I've got the `options=internal_mic_fix` after `cros_debug` but it still doesn't work.

**Comment by PXNDA1234321** [comment]
@sebanc ?

**Comment by sebanc** [comment]
I needed to think about it, here are my 2 last ideas to hopefully fix this:

1)You would need to find your sound card model at:
https://www.kernel.org/doc/html/latest/sound/hd-audio/models.html

And add options snd_hda_intel model=[YOUR_MODEL] to /etc/modprobe/alsa.conf

It works the same on linux, you can also browse the linux forums to find the correct model, an example with a different DELL device (in the first comment):
https://www.linuxquestions.org/questions/linux-laptop-and-netbook-25/internal-microphone-not-working-debian-squeeze-dell-latitude-e6410-854320/

2) Try the "disable_intel_hda" option (chances that it will work are very low)

**Comment by PXNDA1234321** [comment]
Holy shit!

I followed sebanc's advice but it didn't work. I didn't want to give up so using my knowledge of Arch I dug around and tried `dmesg | grep snd`. Voila! My codec showed up. So I knew chromeOS was picking it up, but how should I enable it? I then remembered the alsamixer command. I try it and it works. Okay, only one option. winkey + F6 and changed the card to `HDA Intel PCH`. Now we're talking. winkey + F4 to see capture devices and go to internal mic. DISABLED. FRICKING DISABLED! Smash space bar, capture is now on Head over to https://www.onlinemictest.com/ and yes! It works.

I am not closing this yet as I am still somewhat researching this as I have the `internal_mic_fix` option. I'll try to remove it and see if it works.

**Comment by PXNDA1234321** [comment]
After removing `internal_mic_fix`, the mic still works but with one issue: You have to change the capture to mic after reboot. This might be a one-off though.

**Comment by sebanc** [comment]
What's the output of "aplay -l" ?

Could you post a screen capture of the alsamixer page where you have to unmute the mic ?

**Comment by PXNDA1234321** [comment]
`aplay -l`:
card 0: PCH [HDA Intel PCH], device 0: ALC3235 Analog [ALC3235 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

![Screenshot 2020-12-13 at 9 57 00 AM](https://user-images.githubusercontent.com/53273385/102008587-a0766800-3d29-11eb-93ba-c889fabf59f7.png)
After reboot.

**Comment by sebanc** [comment]
Instead of switching manually the microphone, does `amixer -q -c 0 set "Internal Mic" toggle` has the same effect ?

**Comment by PXNDA1234321** [comment]
Yup, `amixer -q -c 0 set "Internal Mic" toggle` does do the same thing.

**Comment by sebanc** [comment]
That's exactly the command in "internal_mic_fix" so I don't understand why it does not work... could you post a dmesg while "internal_mic_fix is enabled ? (Run "dmesg > ~/Downloads/dmesg.txt" and post dmesg.txt from your Downloads folder)

**Comment by PXNDA1234321** [comment]
[dmesg.txt](https://github.com/sebanc/brunch/files/5684543/dmesg.txt)
Here ya go.

**Comment by sebanc** [comment]
options=internal_mic_fix is not present on the kernel command line (3nd line of the log), do you run `sudo update-grub` after modifying your grub config ?

**Comment by PXNDA1234321** [comment]
I removed it to see if mic still worked. It did and I didn't add it again. Do I need it and what does it do?

**Comment by sebanc** [comment]
No pb, as long as it works, I guess it is ok
